# Generated by Django 6.0.3 on 2026-03-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='discountdetails',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='Discount in percentage (e.g., 10 for 10%)', null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='halal_attribute',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='sypicy',
            field=models.BooleanField(default=False),
        ),
    ]
