# Generated by Django 6.0.3 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0002_remove_menuitems_discountdetails_menuitems_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='price_afterDesc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
