# Generated by Django 6.0.3 on 2026-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0004_featuredcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
