# Generated by Django 6.0.3 on 2026-03-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0005_alter_featuredcategory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='featured_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='vendorapi.featuredcategory'),
        ),
    ]
