# Generated by Django 6.0.3 on 2026-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0007_spotlight_menuitems_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
