# Generated by Django 6.0.3 on 2026-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0008_restaurant_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
