# Generated by Django 6.0.3 on 2026-04-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_created_at_userregister_createdat_and_more'),
        ('vendorapi', '0011_userwallet_userwallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPartyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Mobileno', models.CharField(max_length=15)),
                ('order_details', models.TextField()),
                ('deliveryAdddress', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pary_bookings', to='vendorapi.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_bookings', to='myapi.userregister')),
            ],
        ),
    ]
