# Generated by Django 6.0.3 on 2026-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0012_restaurantpartybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpartybooking',
            name='partydatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantpartybooking',
            name='partytype',
            field=models.CharField(blank=True, choices=[('biryaniparty', 'Biryani Party'), ('birthdayparty', 'Birthday Party'), ('hostalparty', 'Hostal Party')], max_length=100, null=True),
        ),
    ]
