# Generated by Django 6.0.3 on 2026-05-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0013_restaurantpartybooking_partydatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpartybooking',
            name='approvestatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantpartybooking',
            name='enquirystatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100),
        ),
    ]
