# Generated by Django 6.0.3 on 2026-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0014_restaurantpartybooking_approvestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpartybooking',
            name='partydatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
