# Generated by Django 6.0.3 on 2026-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0015_alter_restaurantpartybooking_partydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpartybooking',
            name='enquirystatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='pending', max_length=100),
        ),
    ]
