# Generated by Django 6.0.3 on 2026-03-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
